version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  gcp-auth-deploy:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          name: Authenticate with Google Cloud
          command: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
      - run:
          name: Set Google Cloud Project
          command: gcloud config set project cookson-pro-gcp
      - run:
          name: Clone tf-scripts repo
          command: git clone https://github.com/leecookson/tf-scripts.git
      - run:
          name: Deploy Placeholder
          command: echo "Add your GCP deployment command here"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - gcp-auth-deploy:
          context: GCLOUD_SERVICE_KEY
